export interface LocationData {
  cityName: string;
  postalCode: string;
  region: "Bayern" | "Baden-Württemberg";
  latitude: number;
  longitude: number;
  serviceCities: string[];
}

export const locationData: Record<string, LocationData> = {
  augsburg: {
    cityName: "Augsburg",
    postalCode: "86150",
    region: "Bayern",
    latitude: 48.3705,
    longitude: 10.8978,
    serviceCities: [
      "Augsburg",
      "Bobingen",
      "Königsbrunn",
      "Gersthofen",
      "Neusäß",
      "Stadtbergen",
    ],
  },
  bobingen: {
    cityName: "Bobingen",
    postalCode: "86399",
    region: "Bayern",
    latitude: 48.2744,
    longitude: 10.8369,
    serviceCities: [
      "Bobingen",
      "Augsburg",
      "Königsbrunn",
      "Schwabmünchen",
      "Landsberg am Lech",
    ],
  },
  klosterlechfeld: {
    cityName: "Klosterlechfeld",
    postalCode: "86836",
    region: "Bayern",
    latitude: 48.1547,
    longitude: 10.8308,
    serviceCities: [
      "Klosterlechfeld",
      "Augsburg",
      "Landsberg am Lech",
      "Schwabmünchen",
      "Kaufering",
      "Buchloe",
    ],
  },
  ulm: {
    cityName: "Ulm",
    postalCode: "89073",
    region: "Baden-Württemberg",
    latitude: 48.4011,
    longitude: 9.9876,
    serviceCities: ["Ulm", "Neu-Ulm", "Blaustein", "Laupheim", "Erbach"],
  },
  "neu-ulm": {
    cityName: "Neu-Ulm",
    postalCode: "89231",
    region: "Bayern",
    latitude: 48.3898,
    longitude: 10.0155,
    serviceCities: ["Neu-Ulm", "Ulm", "Illertissen", "Günzburg"],
  },
  memmingen: {
    cityName: "Memmingen",
    postalCode: "87700",
    region: "Bayern",
    latitude: 47.9836,
    longitude: 10.1803,
    serviceCities: [
      "Memmingen",
      "Mindelheim",
      "Ottobeuren",
      "Bad Wurzach",
      "Leutkirch im Allgäu",
    ],
  },
  "landsberg": {
    cityName: "Landsberg am Lech",
    postalCode: "86899",
    region: "Bayern",
    latitude: 48.0511,
    longitude: 10.8735,
    serviceCities: [
      "Landsberg am Lech",
      "Kaufbeuren",
      "Bobingen",
      "Schwabmünchen",
    ],
  },
  koenigsbrunn: {
    cityName: "Königsbrunn",
    postalCode: "86343",
    region: "Bayern",
    latitude: 48.2667,
    longitude: 10.8833,
    serviceCities: ["Königsbrunn", "Augsburg", "Bobingen"],
  },
  gersthofen: {
    cityName: "Gersthofen",
    postalCode: "86368",
    region: "Bayern",
    latitude: 48.4230,
    longitude: 10.8743,
    serviceCities: ["Gersthofen", "Augsburg", "Neusäß"],
  },
  neusaess: {
    cityName: "Neusäß",
    postalCode: "86356",
    region: "Bayern",
    latitude: 48.3986,
    longitude: 10.8377,
    serviceCities: ["Neusäß", "Augsburg", "Gersthofen", "Stadtbergen"],
  },
  stadtbergen: {
    cityName: "Stadtbergen",
    postalCode: "86391",
    region: "Bayern",
    latitude: 48.3636,
    longitude: 10.8461,
    serviceCities: ["Stadtbergen", "Augsburg", "Neusäß"],
  },
  schwabmuenchen: {
    cityName: "Schwabmünchen",
    postalCode: "86830",
    region: "Bayern",
    latitude: 48.1836,
    longitude: 10.7531,
    serviceCities: ["Schwabmünchen", "Bobingen", "Landsberg am Lech"],
  },
  friedberg: {
    cityName: "Friedberg",
    postalCode: "86316",
    region: "Bayern",
    latitude: 48.3576,
    longitude: 10.9842,
    serviceCities: ["Friedberg", "Augsburg", "Aichach"],
  },
  aichach: {
    cityName: "Aichach",
    postalCode: "86551",
    region: "Bayern",
    latitude: 48.4622,
    longitude: 11.1342,
    serviceCities: ["Aichach", "Friedberg", "Augsburg"],
  },
  kaufbeuren: {
    cityName: "Kaufbeuren",
    postalCode: "87600",
    region: "Bayern",
    latitude: 47.8807,
    longitude: 10.6225,
    serviceCities: [
      "Kaufbeuren",
      "Landsberg am Lech",
      "Mindelheim",
      "Bad Wörishofen",
    ],
  },
  mindelheim: {
    cityName: "Mindelheim",
    postalCode: "87719",
    region: "Bayern",
    latitude: 48.0458,
    longitude: 10.4872,
    serviceCities: ["Mindelheim", "Memmingen", "Kaufbeuren", "Ottobeuren"],
  },
  "bad-woerishofen": {
    cityName: "Bad Wörishofen",
    postalCode: "86825",
    region: "Bayern",
    latitude: 48.0014,
    longitude: 10.5972,
    serviceCities: ["Bad Wörishofen", "Mindelheim", "Kaufbeuren"],
  },
  ottobeuren: {
    cityName: "Ottobeuren",
    postalCode: "87724",
    region: "Bayern",
    latitude: 47.9203,
    longitude: 10.2994,
    serviceCities: ["Ottobeuren", "Memmingen", "Mindelheim"],
  },
  "gutenzell-huerbel": {
    cityName: "Gutenzell-Hürbel",
    postalCode: "88484",
    region: "Baden-Württemberg",
    latitude: 48.0667,
    longitude: 9.9500,
    serviceCities: ["Gutenzell-Hürbel", "Biberach", "Laupheim", "Memmingen"],
  },
  blaustein: {
    cityName: "Blaustein",
    postalCode: "89134",
    region: "Baden-Württemberg",
    latitude: 48.4147,
    longitude: 9.9133,
    serviceCities: ["Blaustein", "Ulm", "Laupheim"],
  },
  laupheim: {
    cityName: "Laupheim",
    postalCode: "88471",
    region: "Baden-Württemberg",
    latitude: 48.2297,
    longitude: 9.8784,
    serviceCities: ["Laupheim", "Biberach", "Ulm", "Memmingen"],
  },
  erbach: {
    cityName: "Erbach",
    postalCode: "89155",
    region: "Baden-Württemberg",
    latitude: 48.3258,
    longitude: 9.8961,
    serviceCities: ["Erbach", "Ulm", "Blaustein"],
  },
  guenzburg: {
    cityName: "Günzburg",
    postalCode: "89312",
    region: "Bayern",
    latitude: 48.4550,
    longitude: 10.2739,
    serviceCities: ["Günzburg", "Neu-Ulm", "Krumbach", "Illertissen"],
  },
  krumbach: {
    cityName: "Krumbach",
    postalCode: "86381",
    region: "Bayern",
    latitude: 48.2422,
    longitude: 10.3611,
    serviceCities: ["Krumbach", "Günzburg", "Mindelheim"],
  },
  "bad-wurzach": {
    cityName: "Bad Wurzach",
    postalCode: "88410",
    region: "Baden-Württemberg",
    latitude: 47.9089,
    longitude: 9.9022,
    serviceCities: ["Bad Wurzach", "Memmingen", "Leutkirch im Allgäu"],
  },
  leutkirch: {
    cityName: "Leutkirch im Allgäu",
    postalCode: "88299",
    region: "Baden-Württemberg",
    latitude: 47.8250,
    longitude: 10.0231,
    serviceCities: [
      "Leutkirch im Allgäu",
      "Memmingen",
      "Bad Wurzach",
      "Isny im Allgäu",
    ],
  },
};
